In [28]:
import pandas as pd

In [29]:
df1=pd.read_csv("../data/raw/stock_data/adanienterprises.csv")
df2=pd.read_csv("../data/raw/market_data/bsesensex.csv")

In [30]:
df1.head()

         Date  day_return_adani enterprises
0  2023-04-03                    -18.852296
1  2023-04-05                    -11.324901
2  2023-04-06                     28.768357
3  2023-04-10                     13.105975
4  2023-04-11                     -3.784517

In [31]:
df2.head()

         Date  day_return_bse sensex
0  2023-04-03              -0.418033
1  2023-04-05              10.061775
2  2023-04-06               3.454089
3  2023-04-10              -0.208302
4  2023-04-11               2.150928

In [32]:
dat1=df1["Date"].to_list()
dat2=df2["Date"].to_list()

In [33]:
extra_values = list(set(dat1).symmetric_difference(set(dat2)))
print("Extra values not common in both lists:")
print(extra_values)

Extra values not common in both lists:
['2025-02-01', '2024-01-01', '2026-01-15']

In [34]:
df1.shape,df2.shape

((740, 2), (737, 2))

In [35]:
df=df1.merge(df2,on="Date",how="outer")
df.head()

         Date  day_return_adani enterprises  day_return_bse sensex
0  2023-04-03                    -18.852296              -0.418033
1  2023-04-05                    -11.324901              10.061775
2  2023-04-06                     28.768357               3.454089
3  2023-04-10                     13.105975              -0.208302
4  2023-04-11                     -3.784517               2.150928

In [36]:
df.shape

(740, 3)

In [37]:
df=df.ffill()

In [38]:
df[df.isnull().any(axis=1)].shape

(0, 3)