In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("../data/preprocessed/stock_data_stacked.csv")
df.head()

,Date,day_return_scaled,RSI,Sortino,MACD,emaslope_15d,tr,atr_15d,bb_width_15d,zscore_15d,ret_15d,max_dd_15d,vol_15d,sharpe_ratio_15,var95_15,cvar95_15,beta_15,alpha_5d,Target,stock_name
0,2023-04-03,-18.852296,58.401717,0.091039,0.000000,0.940924,7.527394,18.00498,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,-11.324901,adanienterprises
1,2023-04-05,-11.324901,58.401717,0.091039,-0.600476,0.940924,7.527394,18.00498,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,28.768357,adanienterprises
2,2023-04-06,28.768357,58.401717,0.091039,-4.262414,5.834966,40.093258,18.00498,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,13.105975,adanienterprises
3,2023-04-10,13.105975,58.401717,0.091039,-5.833458,3.147798,15.662382,18.00498,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,-3.784517,adanienterprises
4,2023-04-11,-3.784517,58.401717,0.091039,-5.650466,0.643011,16.890492,18.00498,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,18.329658,adanienterprises

In [4]:
print(df.head())

         Date  day_return_scaled        RSI   Sortino      MACD  emaslope_15d  \
0  2023-04-03         -18.852296  58.401717  0.091039  0.000000      0.940924
1  2023-04-05         -11.324901  58.401717  0.091039 -0.600476      0.940924
2  2023-04-06          28.768357  58.401717  0.091039 -4.262414      5.834966
3  2023-04-10          13.105975  58.401717  0.091039 -5.833458      3.147798
4  2023-04-11          -3.784517  58.401717  0.091039 -5.650466      0.643011

          tr   atr_15d  bb_width_15d  zscore_15d   ret_15d  max_dd_15d  \
0   7.527394  18.00498    115.680398   -0.243931 -1.144954   -2.368649
1   7.527394  18.00498    115.680398   -0.243931 -1.144954   -2.368649
2  40.093258  18.00498    115.680398   -0.243931 -1.144954   -2.368649
3  15.662382  18.00498    115.680398   -0.243931 -1.144954   -2.368649
4  16.890492  18.00498    115.680398   -0.243931 -1.144954   -2.368649

      vol_15d  sharpe_ratio_15   var95_15  cvar95_15   beta_15  alpha_5d  \
0  249.482515         0.032661 -22.175733 -23.293608 -0.152004 -4.344402
1  249.482515         0.032661 -22.175733 -23.293608 -0.152004 -4.344402
2  249.482515         0.032661 -22.175733 -23.293608 -0.152004 -4.344402
3  249.482515         0.032661 -22.175733 -23.293608 -0.152004 -4.344402
4  249.482515         0.032661 -22.175733 -23.293608 -0.152004 -4.344402

      Target        stock_name
0 -11.324901  adanienterprises
1  28.768357  adanienterprises
2  13.105975  adanienterprises
3  -3.784517  adanienterprises
4  18.329658  adanienterprises

In [5]:
df = df.sort_values("Date")

In [6]:
df["stock_id"] = df["stock_name"].astype("category").cat.codes
df = df.drop(columns=["stock_name"])

In [7]:
df

,Date,day_return_scaled,RSI,Sortino,MACD,emaslope_15d,tr,atr_15d,bb_width_15d,zscore_15d,ret_15d,max_dd_15d,vol_15d,sharpe_ratio_15,var95_15,cvar95_15,beta_15,alpha_5d,Target,stock_id
0,2023-04-03,-18.852296,58.401717,0.091039,0.000000,0.940924,7.527394,18.004980,115.680398,-0.243931,-1.144954,-2.368649,249.482515,0.032661,-22.175733,-23.293608,-0.152004,-4.344402,-11.324901,0
11100,2023-04-03,6.747483,40.972534,0.690688,0.000000,-0.349164,2.793314,6.528095,10.630257,-0.274065,1.503088,-2.234391,90.987583,0.355523,-6.661356,-6.677204,0.828898,-6.700847,3.954169,15
14060,2023-04-03,12.528456,46.073054,-0.296502,0.000000,-3.248621,25.988967,12.894444,-22.045049,-0.478526,-0.553958,-2.356114,175.725292,-0.171468,-16.197536,-16.761346,0.646957,7.896448,-13.460511,19
11840,2023-04-03,-4.518393,53.457808,0.127946,0.000000,5.619523,44.956181,12.027371,36.109901,0.758886,-3.902934,-2.116308,229.809172,0.104658,-16.940169,-19.811843,-0.107677,-0.229626,40.437788,16
9620,2023-04-03,-13.281306,54.639391,0.943234,0.000000,4.134441,33.075527,15.551249,9.650895,-0.358013,-1.694122,-2.047071,170.637402,0.391619,-11.375981,-13.281306,1.078691,-0.344950,19.794221,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5179,2026-04-02,2.016827,49.691832,-0.588650,2.469642,1.203410,49.108441,15.223127,-9.052474,0.570926,-0.745880,-3.653397,248.075781,-0.417538,-31.012441,-47.091614,-0.089347,0.064163,NaN,6
5919,2026-04-02,25.094778,52.129595,-0.302815,2.653254,4.135311,80.094797,22.732699,-20.000893,1.431666,0.215117,-3.194644,323.435408,-0.188983,-37.992632,-55.000019,-0.078485,-0.894565,NaN,7
14799,2026-04-02,-0.833500,48.735160,-0.409867,4.745398,0.792312,42.832890,20.708456,-15.304179,0.211391,-0.958325,-2.432864,264.756316,-0.246979,-26.319250,-43.666390,0.084270,0.573389,NaN,19
3699,2026-04-02,22.064247,58.745824,-0.390717,0.871518,3.980715,40.676159,26.211910,-12.782217,1.196850,-3.055001,-3.345840,396.258755,-0.295703,-41.387171,-41.465100,-0.014320,-1.145440,NaN,4
21459,2026-04-02,23.149626,55.665096,-0.507963,-2.358111,3.383947,24.872783,15.250852,-14.752400,2.169601,9.794370,-1.770762,193.572245,-0.256221,-18.678479,-18.871757,0.205207,5.414422,NaN,28

In [8]:
df.dropna(inplace=True)

In [9]:
df["Target"]=df["Target"].apply(lambda x: 1 if x > 0 else 0)

In [10]:
df["Date"] = pd.to_datetime(df["Date"])

train = df[(df["Date"] >= "2023-04-03") & (df["Date"] <= "2024-12-31")]
val   = df[(df["Date"] >= "2025-01-01") & (df["Date"] <= "2025-06-30")]
test  = df[(df["Date"] >= "2025-07-01") & (df["Date"] <= "2026-04-02")]

In [11]:
features = [col for col in df.columns if col not in ["Date", "Target"]]

X_train, y_train = train[features], train["Target"]
X_val, y_val     = val[features], val["Target"]
X_test, y_test   = test[features], test["Target"]

In [14]:
X_train.columns

Index(['day_return_scaled', 'RSI', 'Sortino', 'MACD', 'emaslope_15d', 'tr',
       'atr_15d', 'bb_width_15d', 'zscore_15d', 'ret_15d', 'max_dd_15d',
       'vol_15d', 'sharpe_ratio_15', 'var95_15', 'cvar95_15', 'beta_15',
       'alpha_5d', 'stock_id'],
      dtype='str')

In [ ]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=True
)

[0]	validation_0-logloss:0.69204
[1]	validation_0-logloss:0.69186
[2]	validation_0-logloss:0.69172
[3]	validation_0-logloss:0.69178
[4]	validation_0-logloss:0.69198
[5]	validation_0-logloss:0.69179
[6]	validation_0-logloss:0.69182
[7]	validation_0-logloss:0.69184
[8]	validation_0-logloss:0.69209
[9]	validation_0-logloss:0.69203
[10]	validation_0-logloss:0.69205
[11]	validation_0-logloss:0.69198
[12]	validation_0-logloss:0.69202
[13]	validation_0-logloss:0.69212
[14]	validation_0-logloss:0.69215
[15]	validation_0-logloss:0.69210
[16]	validation_0-logloss:0.69212
[17]	validation_0-logloss:0.69215
[18]	validation_0-logloss:0.69206
[19]	validation_0-logloss:0.69195
[20]	validation_0-logloss:0.69200
[21]	validation_0-logloss:0.69214
[22]	validation_0-logloss:0.69216
[23]	validation_0-logloss:0.69217
[24]	validation_0-logloss:0.69220
[25]	validation_0-logloss:0.69216
[26]	validation_0-logloss:0.69241
[27]	validation_0-logloss:0.69242
[28]	validation_0-logloss:0.69242
[29]	validation_0-logloss:0.69249
[30]	validation_0-logloss:0.69273
[31]	validation_0-logloss:0.69276
[32]	validation_0-logloss:0.69281
[33]	validation_0-logloss:0.69287
[34]	validation_0-logloss:0.69293
[35]	validation_0-logloss:0.69300
[36]	validation_0-logloss:0.69295
[37]	validation_0-logloss:0.69301
[38]	validation_0-logloss:0.69290
[39]	validation_0-logloss:0.69285
[40]	validation_0-logloss:0.69298
[41]	validation_0-logloss:0.69315
[42]	validation_0-logloss:0.69338
[43]	validation_0-logloss:0.69346
[44]	validation_0-logloss:0.69341
[45]	validation_0-logloss:0.69345
[46]	validation_0-logloss:0.69349
[47]	validation_0-logloss:0.69354
[48]	validation_0-logloss:0.69352
[49]	validation_0-logloss:0.69347
[50]	validation_0-logloss:0.69347
[51]	validation_0-logloss:0.69346
[52]	validation_0-logloss:0.69351
[53]	validation_0-logloss:0.69344
[54]	validation_0-logloss:0.69346
[55]	validation_0-logloss:0.69344
[56]	validation_0-logloss:0.69368
[57]	validation_0-logloss:0.69350
[58]	validation_0-logloss:0.69351
[59]	validation_0-logloss:0.69360
[60]	validation_0-logloss:0.69363
[61]	validation_0-logloss:0.69371
[62]	validation_0-logloss:0.69406
[63]	validation_0-logloss:0.69429
[64]	validation_0-logloss:0.69439
[65]	validation_0-logloss:0.69453
[66]	validation_0-logloss:0.69463
[67]	validation_0-logloss:0.69472
[68]	validation_0-logloss:0.69473
[69]	validation_0-logloss:0.69483
[70]	validation_0-logloss:0.69485
[71]	validation_0-logloss:0.69495
[72]	validation_0-logloss:0.69498
[73]	validation_0-logloss:0.69501
[74]	validation_0-logloss:0.69510
[75]	validation_0-logloss:0.69516
[76]	validation_0-logloss:0.69528
[77]	validation_0-logloss:0.69540
[78]	validation_0-logloss:0.69538
[79]	validation_0-logloss:0.69549
[80]	validation_0-logloss:0.69561
[81]	validation_0-logloss:0.69569
[82]	validation_0-logloss:0.69577
[83]	validation_0-logloss:0.69585
[84]	validation_0-logloss:0.69582
[85]	validation_0-logloss:0.69592
[86]	validation_0-logloss:0.69595
[87]	validation_0-logloss:0.69601
[88]	validation_0-logloss:0.69599
[89]	validation_0-logloss:0.69606
[90]	validation_0-logloss:0.69622
[91]	validation_0-logloss:0.69636
[92]	validation_0-logloss:0.69639
[93]	validation_0-logloss:0.69633
[94]	validation_0-logloss:0.69612
[95]	validation_0-logloss:0.69626
[96]	validation_0-logloss:0.69635
[97]	validation_0-logloss:0.69649
[98]	validation_0-logloss:0.69648
[99]	validation_0-logloss:0.69652
[100]	validation_0-logloss:0.69634
[101]	validation_0-logloss:0.69622
[102]	validation_0-logloss:0.69636
[103]	validation_0-logloss:0.69670
[104]	validation_0-logloss:0.69692
[105]	validation_0-logloss:0.69709
[106]	validation_0-logloss:0.69701
[107]	validation_0-logloss:0.69709
[108]	validation_0-logloss:0.69722
[109]	validation_0-logloss:0.69724
[110]	validation_0-logloss:0.69722
[111]	validation_0-logloss:0.69721
[112]	validation_0-logloss:0.69735
[113]	validation_0-logloss:0.69733
[114]	validation_0-logloss:0.69736
[115]	validation_0-logloss:0.69759
[116]	validation_0-logloss:0.69766
[117]	validation_0-logloss:0.69773
[118]	validation_0-logloss:0.69764
[119]	validation_0-logloss:0.69761
[120]	validation_0-logloss:0.69779
[121]	validation_0-logloss:0.69792
[122]	validation_0-logloss:0.69788
[123]	validation_0-logloss:0.69795
[124]	validation_0-logloss:0.69799
[125]	validation_0-logloss:0.69796
[126]	validation_0-logloss:0.69814
[127]	validation_0-logloss:0.69820
[128]	validation_0-logloss:0.69806
[129]	validation_0-logloss:0.69821
[130]	validation_0-logloss:0.69826
[131]	validation_0-logloss:0.69823
[132]	validation_0-logloss:0.69819
[133]	validation_0-logloss:0.69833
[134]	validation_0-logloss:0.69828
[135]	validation_0-logloss:0.69840
[136]	validation_0-logloss:0.69845
[137]	validation_0-logloss:0.69836
[138]	validation_0-logloss:0.69827
[139]	validation_0-logloss:0.69833
[140]	validation_0-logloss:0.69813
[141]	validation_0-logloss:0.69813
[142]	validation_0-logloss:0.69815
[143]	validation_0-logloss:0.69823
[144]	validation_0-logloss:0.69824
[145]	validation_0-logloss:0.69840
[146]	validation_0-logloss:0.69840
[147]	validation_0-logloss:0.69841
[148]	validation_0-logloss:0.69846
[149]	validation_0-logloss:0.69846
[150]	validation_0-logloss:0.69860
[151]	validation_0-logloss:0.69870
[152]	validation_0-logloss:0.69869
[153]	validation_0-logloss:0.69875
[154]	validation_0-logloss:0.69888
[155]	validation_0-logloss:0.69893
[156]	validation_0-logloss:0.69896
[157]	validation_0-logloss:0.69899
[158]	validation_0-logloss:0.69907
[159]	validation_0-logloss:0.69909
[160]	validation_0-logloss:0.69895
[161]	validation_0-logloss:0.69909
[162]	validation_0-logloss:0.69925
[163]	validation_0-logloss:0.69922
[164]	validation_0-logloss:0.69946
[165]	validation_0-logloss:0.69948
[166]	validation_0-logloss:0.69936
[167]	validation_0-logloss:0.69914
[168]	validation_0-logloss:0.69922
[169]	validation_0-logloss:0.69931
[170]	validation_0-logloss:0.69937
[171]	validation_0-logloss:0.69943
[172]	validation_0-logloss:0.69943
[173]	validation_0-logloss:0.69960
[174]	validation_0-logloss:0.69961
[175]	validation_0-logloss:0.69968
[176]	validation_0-logloss:0.69972
[177]	validation_0-logloss:0.69987
[178]	validation_0-logloss:0.69994
[179]	validation_0-logloss:0.70007
[180]	validation_0-logloss:0.70031
[181]	validation_0-logloss:0.70027
[182]	validation_0-logloss:0.70032
[183]	validation_0-logloss:0.70031
[184]	validation_0-logloss:0.70053
[185]	validation_0-logloss:0.70070
[186]	validation_0-logloss:0.70065
[187]	validation_0-logloss:0.70059
[188]	validation_0-logloss:0.70069
[189]	validation_0-logloss:0.70081
[190]	validation_0-logloss:0.70086
[191]	validation_0-logloss:0.70094
[192]	validation_0-logloss:0.70104
[193]	validation_0-logloss:0.70132
[194]	validation_0-logloss:0.70141
[195]	validation_0-logloss:0.70126
[196]	validation_0-logloss:0.70134
[197]	validation_0-logloss:0.70135
[198]	validation_0-logloss:0.70145
[199]	validation_0-logloss:0.70157
[200]	validation_0-logloss:0.70168
[201]	validation_0-logloss:0.70168
[202]	validation_0-logloss:0.70177
[203]	validation_0-logloss:0.70184
[204]	validation_0-logloss:0.70187
[205]	validation_0-logloss:0.70201
[206]	validation_0-logloss:0.70219
[207]	validation_0-logloss:0.70221
[208]	validation_0-logloss:0.70227
[209]	validation_0-logloss:0.70236
[210]	validation_0-logloss:0.70245
[211]	validation_0-logloss:0.70247
[212]	validation_0-logloss:0.70258
[213]	validation_0-logloss:0.70255
[214]	validation_0-logloss:0.70248
[215]	validation_0-logloss:0.70267
[216]	validation_0-logloss:0.70260
[217]	validation_0-logloss:0.70270
[218]	validation_0-logloss:0.70272
[219]	validation_0-logloss:0.70273
[220]	validation_0-logloss:0.70278
[221]	validation_0-logloss:0.70290
[222]	validation_0-logloss:0.70292
[223]	validation_0-logloss:0.70293
[224]	validation_0-logloss:0.70290
[225]	validation_0-logloss:0.70293
[226]	validation_0-logloss:0.70298
[227]	validation_0-logloss:0.70314
[228]	validation_0-logloss:0.70329
[229]	validation_0-logloss:0.70335
[230]	validation_0-logloss:0.70329
[231]	validation_0-logloss:0.70333
[232]	validation_0-logloss:0.70334
[233]	validation_0-logloss:0.70335
[234]	validation_0-logloss:0.70345
[235]	validation_0-logloss:0.70349
[236]	validation_0-logloss:0.70345
[237]	validation_0-logloss:0.70353
[238]	validation_0-logloss:0.70366
[239]	validation_0-logloss:0.70349
[240]	validation_0-logloss:0.70351
[241]	validation_0-logloss:0.70350
[242]	validation_0-logloss:0.70355
[243]	validation_0-logloss:0.70367
[244]	validation_0-logloss:0.70395
[245]	validation_0-logloss:0.70395
[246]	validation_0-logloss:0.70403
[247]	validation_0-logloss:0.70402
[248]	validation_0-logloss:0.70409
[249]	validation_0-logloss:0.70408
[250]	validation_0-logloss:0.70400
[251]	validation_0-logloss:0.70400
[252]	validation_0-logloss:0.70397
[253]	validation_0-logloss:0.70399
[254]	validation_0-logloss:0.70404
[255]	validation_0-logloss:0.70409
[256]	validation_0-logloss:0.70408
[257]	validation_0-logloss:0.70416
[258]	validation_0-logloss:0.70415
[259]	validation_0-logloss:0.70398
[260]	validation_0-logloss:0.70415
[261]	validation_0-logloss:0.70428
[262]	validation_0-logloss:0.70414
[263]	validation_0-logloss:0.70411
[264]	validation_0-logloss:0.70426
[265]	validation_0-logloss:0.70443
[266]	validation_0-logloss:0.70444
[267]	validation_0-logloss:0.70466
[268]	validation_0-logloss:0.70487
[269]	validation_0-logloss:0.70493
[270]	validation_0-logloss:0.70506
[271]	validation_0-logloss:0.70516
[272]	validation_0-logloss:0.70516
[273]	validation_0-logloss:0.70530
[274]	validation_0-logloss:0.70533
[275]	validation_0-logloss:0.70545
[276]	validation_0-logloss:0.70552
[277]	validation_0-logloss:0.70557
[278]	validation_0-logloss:0.70571
[279]	validation_0-logloss:0.70567
[280]	validation_0-logloss:0.70568
[281]	validation_0-logloss:0.70574
[282]	validation_0-logloss:0.70604
[283]	validation_0-logloss:0.70606
[284]	validation_0-logloss:0.70609
[285]	validation_0-logloss:0.70616
[286]	validation_0-logloss:0.70623
[287]	validation_0-logloss:0.70629
[288]	validation_0-logloss:0.70624
[289]	validation_0-logloss:0.70640
[290]	validation_0-logloss:0.70648
[291]	validation_0-logloss:0.70659
[292]	validation_0-logloss:0.70656
[293]	validation_0-logloss:0.70667
[294]	validation_0-logloss:0.70665
[295]	validation_0-logloss:0.70684
[296]	validation_0-logloss:0.70675
[297]	validation_0-logloss:0.70660
[298]	validation_0-logloss:0.70658
[299]	validation_0-logloss:0.70665
[300]	validation_0-logloss:0.70677
[301]	validation_0-logloss:0.70689
[302]	validation_0-logloss:0.70676
[303]	validation_0-logloss:0.70676
[304]	validation_0-logloss:0.70675
[305]	validation_0-logloss:0.70690
[306]	validation_0-logloss:0.70706
[307]	validation_0-logloss:0.70707
[308]	validation_0-logloss:0.70727
[309]	validation_0-logloss:0.70730
[310]	validation_0-logloss:0.70730
[311]	validation_0-logloss:0.70736
[312]	validation_0-logloss:0.70740
[313]	validation_0-logloss:0.70740
[314]	validation_0-logloss:0.70740
[315]	validation_0-logloss:0.70746
[316]	validation_0-logloss:0.70767
[317]	validation_0-logloss:0.70773
[318]	validation_0-logloss:0.70775
[319]	validation_0-logloss:0.70789
[320]	validation_0-logloss:0.70808
[321]	validation_0-logloss:0.70824
[322]	validation_0-logloss:0.70834
[323]	validation_0-logloss:0.70836
[324]	validation_0-logloss:0.70830
[325]	validation_0-logloss:0.70815
[326]	validation_0-logloss:0.70804
[327]	validation_0-logloss:0.70803
[328]	validation_0-logloss:0.70806
[329]	validation_0-logloss:0.70820
[330]	validation_0-logloss:0.70826
[331]	validation_0-logloss:0.70832
[332]	validation_0-logloss:0.70838
[333]	validation_0-logloss:0.70852
[334]	validation_0-logloss:0.70852
[335]	validation_0-logloss:0.70865
[336]	validation_0-logloss:0.70863
[337]	validation_0-logloss:0.70861
[338]	validation_0-logloss:0.70874
[339]	validation_0-logloss:0.70873
[340]	validation_0-logloss:0.70870
[341]	validation_0-logloss:0.70878
[342]	validation_0-logloss:0.70879
[343]	validation_0-logloss:0.70888
[344]	validation_0-logloss:0.70899
[345]	validation_0-logloss:0.70901
[346]	validation_0-logloss:0.70905
[347]	validation_0-logloss:0.70914
[348]	validation_0-logloss:0.70909
[349]	validation_0-logloss:0.70916
[350]	validation_0-logloss:0.70926
[351]	validation_0-logloss:0.70944
[352]	validation_0-logloss:0.70940
[353]	validation_0-logloss:0.70936
[354]	validation_0-logloss:0.70951
[355]	validation_0-logloss:0.70969
[356]	validation_0-logloss:0.70962
[357]	validation_0-logloss:0.70970
[358]	validation_0-logloss:0.70989
[359]	validation_0-logloss:0.71000
[360]	validation_0-logloss:0.70999
[361]	validation_0-logloss:0.71001
[362]	validation_0-logloss:0.71005
[363]	validation_0-logloss:0.71008
[364]	validation_0-logloss:0.71017
[365]	validation_0-logloss:0.71019
[366]	validation_0-logloss:0.71031
[367]	validation_0-logloss:0.71046
[368]	validation_0-logloss:0.71059
[369]	validation_0-logloss:0.71055
[370]	validation_0-logloss:0.71049
[371]	validation_0-logloss:0.71053
[372]	validation_0-logloss:0.71063
[373]	validation_0-logloss:0.71061
[374]	validation_0-logloss:0.71059
[375]	validation_0-logloss:0.71071
[376]	validation_0-logloss:0.71083
[377]	validation_0-logloss:0.71087
[378]	validation_0-logloss:0.71097
[379]	validation_0-logloss:0.71103
[380]	validation_0-logloss:0.71121
[381]	validation_0-logloss:0.71137
[382]	validation_0-logloss:0.71131
[383]	validation_0-logloss:0.71124
[384]	validation_0-logloss:0.71119
[385]	validation_0-logloss:0.71123
[386]	validation_0-logloss:0.71127
[387]	validation_0-logloss:0.71136
[388]	validation_0-logloss:0.71150
[389]	validation_0-logloss:0.71160
[390]	validation_0-logloss:0.71163
[391]	validation_0-logloss:0.71163
[392]	validation_0-logloss:0.71164
[393]	validation_0-logloss:0.71172
[394]	validation_0-logloss:0.71171
[395]	validation_0-logloss:0.71169
[396]	validation_0-logloss:0.71180
[397]	validation_0-logloss:0.71182
[398]	validation_0-logloss:0.71185
[399]	validation_0-logloss:0.71190
[400]	validation_0-logloss:0.71189
[401]	validation_0-logloss:0.71215
[402]	validation_0-logloss:0.71224
[403]	validation_0-logloss:0.71220
[404]	validation_0-logloss:0.71221
[405]	validation_0-logloss:0.71228
[406]	validation_0-logloss:0.71232
[407]	validation_0-logloss:0.71222
[408]	validation_0-logloss:0.71220
[409]	validation_0-logloss:0.71223
[410]	validation_0-logloss:0.71238
[411]	validation_0-logloss:0.71242
[412]	validation_0-logloss:0.71239
[413]	validation_0-logloss:0.71237
[414]	validation_0-logloss:0.71232
[415]	validation_0-logloss:0.71226
[416]	validation_0-logloss:0.71240
[417]	validation_0-logloss:0.71240
[418]	validation_0-logloss:0.71247
[419]	validation_0-logloss:0.71265
[420]	validation_0-logloss:0.71283
[421]	validation_0-logloss:0.71268
[422]	validation_0-logloss:0.71265
[423]	validation_0-logloss:0.71272
[424]	validation_0-logloss:0.71274
[425]	validation_0-logloss:0.71267
[426]	validation_0-logloss:0.71266
[427]	validation_0-logloss:0.71273
[428]	validation_0-logloss:0.71277
[429]	validation_0-logloss:0.71275
[430]	validation_0-logloss:0.71275
[431]	validation_0-logloss:0.71279
[432]	validation_0-logloss:0.71295
[433]	validation_0-logloss:0.71292
[434]	validation_0-logloss:0.71304
[435]	validation_0-logloss:0.71301
[436]	validation_0-logloss:0.71302
[437]	validation_0-logloss:0.71298
[438]	validation_0-logloss:0.71303
[439]	validation_0-logloss:0.71318
[440]	validation_0-logloss:0.71313
[441]	validation_0-logloss:0.71318
[442]	validation_0-logloss:0.71335
[443]	validation_0-logloss:0.71334
[444]	validation_0-logloss:0.71338
[445]	validation_0-logloss:0.71344
[446]	validation_0-logloss:0.71355
[447]	validation_0-logloss:0.71366
[448]	validation_0-logloss:0.71387
[449]	validation_0-logloss:0.71389
[450]	validation_0-logloss:0.71403
[451]	validation_0-logloss:0.71420
[452]	validation_0-logloss:0.71420
[453]	validation_0-logloss:0.71433
[454]	validation_0-logloss:0.71440
[455]	validation_0-logloss:0.71444
[456]	validation_0-logloss:0.71441
[457]	validation_0-logloss:0.71435
[458]	validation_0-logloss:0.71443
[459]	validation_0-logloss:0.71441
[460]	validation_0-logloss:0.71444
[461]	validation_0-logloss:0.71457
[462]	validation_0-logloss:0.71469
[463]	validation_0-logloss:0.71477
[464]	validation_0-logloss:0.71487
[465]	validation_0-logloss:0.71517
[466]	validation_0-logloss:0.71519
[467]	validation_0-logloss:0.71531
[468]	validation_0-logloss:0.71511
[469]	validation_0-logloss:0.71509
[470]	validation_0-logloss:0.71527
[471]	validation_0-logloss:0.71545
[472]	validation_0-logloss:0.71549
[473]	validation_0-logloss:0.71546
[474]	validation_0-logloss:0.71550
[475]	validation_0-logloss:0.71547
[476]	validation_0-logloss:0.71540
[477]	validation_0-logloss:0.71543
[478]	validation_0-logloss:0.71543
[479]	validation_0-logloss:0.71558
[480]	validation_0-logloss:0.71560
[481]	validation_0-logloss:0.71560
[482]	validation_0-logloss:0.71563
[483]	validation_0-logloss:0.71571
[484]	validation_0-logloss:0.71581
[485]	validation_0-logloss:0.71584
[486]	validation_0-logloss:0.71584
[487]	validation_0-logloss:0.71593
[488]	validation_0-logloss:0.71596
[489]	validation_0-logloss:0.71605
[490]	validation_0-logloss:0.71604
[491]	validation_0-logloss:0.71607
[492]	validation_0-logloss:0.71610
[493]	validation_0-logloss:0.71619
[494]	validation_0-logloss:0.71609
[495]	validation_0-logloss:0.71601
[496]	validation_0-logloss:0.71607
[497]	validation_0-logloss:0.71624
[498]	validation_0-logloss:0.71646
[499]	validation_0-logloss:0.71644

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix

predictions = model.predict(X_test)

print("Classification Report:\n")
print(classification_report(y_test, predictions, target_names=["Down/No Gain", "Up"]))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, predictions))

Classification Report:

              precision    recall  f1-score   support

Down/No Gain       0.58      0.77      0.66      3128
          Up       0.45      0.26      0.33      2295

    accuracy                           0.55      5423
   macro avg       0.52      0.51      0.50      5423
weighted avg       0.53      0.55      0.52      5423


Confusion Matrix:

[[2405  723]
 [1707  588]]

In [39]:
model = XGBClassifier(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    scale_pos_weight=1.36
)

model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=True
)

[0]	validation_0-logloss:0.69465
[1]	validation_0-logloss:0.69438
[2]	validation_0-logloss:0.69418
[3]	validation_0-logloss:0.69406
[4]	validation_0-logloss:0.69447
[5]	validation_0-logloss:0.69429
[6]	validation_0-logloss:0.69425
[7]	validation_0-logloss:0.69410
[8]	validation_0-logloss:0.69442
[9]	validation_0-logloss:0.69439
[10]	validation_0-logloss:0.69441
[11]	validation_0-logloss:0.69442
[12]	validation_0-logloss:0.69434
[13]	validation_0-logloss:0.69442
[14]	validation_0-logloss:0.69445
[15]	validation_0-logloss:0.69425
[16]	validation_0-logloss:0.69432
[17]	validation_0-logloss:0.69434
[18]	validation_0-logloss:0.69434
[19]	validation_0-logloss:0.69432
[20]	validation_0-logloss:0.69441
[21]	validation_0-logloss:0.69451
[22]	validation_0-logloss:0.69454
[23]	validation_0-logloss:0.69458
[24]	validation_0-logloss:0.69466
[25]	validation_0-logloss:0.69455
[26]	validation_0-logloss:0.69466
[27]	validation_0-logloss:0.69465
[28]	validation_0-logloss:0.69465
[29]	validation_0-logloss:0.69457
[30]	validation_0-logloss:0.69471
[31]	validation_0-logloss:0.69467
[32]	validation_0-logloss:0.69469
[33]	validation_0-logloss:0.69472
[34]	validation_0-logloss:0.69491
[35]	validation_0-logloss:0.69497
[36]	validation_0-logloss:0.69508
[37]	validation_0-logloss:0.69513
[38]	validation_0-logloss:0.69501
[39]	validation_0-logloss:0.69488
[40]	validation_0-logloss:0.69502
[41]	validation_0-logloss:0.69515
[42]	validation_0-logloss:0.69536
[43]	validation_0-logloss:0.69546
[44]	validation_0-logloss:0.69538
[45]	validation_0-logloss:0.69535
[46]	validation_0-logloss:0.69543
[47]	validation_0-logloss:0.69546
[48]	validation_0-logloss:0.69559
[49]	validation_0-logloss:0.69550
[50]	validation_0-logloss:0.69552
[51]	validation_0-logloss:0.69566
[52]	validation_0-logloss:0.69571
[53]	validation_0-logloss:0.69584
[54]	validation_0-logloss:0.69579
[55]	validation_0-logloss:0.69572
[56]	validation_0-logloss:0.69589
[57]	validation_0-logloss:0.69576
[58]	validation_0-logloss:0.69609
[59]	validation_0-logloss:0.69620
[60]	validation_0-logloss:0.69610
[61]	validation_0-logloss:0.69600
[62]	validation_0-logloss:0.69625
[63]	validation_0-logloss:0.69648
[64]	validation_0-logloss:0.69651
[65]	validation_0-logloss:0.69665
[66]	validation_0-logloss:0.69676
[67]	validation_0-logloss:0.69685
[68]	validation_0-logloss:0.69683
[69]	validation_0-logloss:0.69695
[70]	validation_0-logloss:0.69709
[71]	validation_0-logloss:0.69704
[72]	validation_0-logloss:0.69685
[73]	validation_0-logloss:0.69677
[74]	validation_0-logloss:0.69683
[75]	validation_0-logloss:0.69686
[76]	validation_0-logloss:0.69704
[77]	validation_0-logloss:0.69710
[78]	validation_0-logloss:0.69714
[79]	validation_0-logloss:0.69729
[80]	validation_0-logloss:0.69723
[81]	validation_0-logloss:0.69742
[82]	validation_0-logloss:0.69744
[83]	validation_0-logloss:0.69752
[84]	validation_0-logloss:0.69759
[85]	validation_0-logloss:0.69769
[86]	validation_0-logloss:0.69782
[87]	validation_0-logloss:0.69794
[88]	validation_0-logloss:0.69800
[89]	validation_0-logloss:0.69810
[90]	validation_0-logloss:0.69835
[91]	validation_0-logloss:0.69846
[92]	validation_0-logloss:0.69851
[93]	validation_0-logloss:0.69837
[94]	validation_0-logloss:0.69826
[95]	validation_0-logloss:0.69821
[96]	validation_0-logloss:0.69831
[97]	validation_0-logloss:0.69845
[98]	validation_0-logloss:0.69850
[99]	validation_0-logloss:0.69858
[100]	validation_0-logloss:0.69854
[101]	validation_0-logloss:0.69850
[102]	validation_0-logloss:0.69869
[103]	validation_0-logloss:0.69886
[104]	validation_0-logloss:0.69916
[105]	validation_0-logloss:0.69943
[106]	validation_0-logloss:0.69938
[107]	validation_0-logloss:0.69941
[108]	validation_0-logloss:0.69943
[109]	validation_0-logloss:0.69980
[110]	validation_0-logloss:0.69984
[111]	validation_0-logloss:0.69980
[112]	validation_0-logloss:0.69988
[113]	validation_0-logloss:0.70001
[114]	validation_0-logloss:0.70004
[115]	validation_0-logloss:0.70012
[116]	validation_0-logloss:0.70013
[117]	validation_0-logloss:0.70009
[118]	validation_0-logloss:0.70028
[119]	validation_0-logloss:0.70034
[120]	validation_0-logloss:0.70047
[121]	validation_0-logloss:0.70057
[122]	validation_0-logloss:0.70043
[123]	validation_0-logloss:0.70053
[124]	validation_0-logloss:0.70045
[125]	validation_0-logloss:0.70057
[126]	validation_0-logloss:0.70073
[127]	validation_0-logloss:0.70084
[128]	validation_0-logloss:0.70105
[129]	validation_0-logloss:0.70114
[130]	validation_0-logloss:0.70111
[131]	validation_0-logloss:0.70122
[132]	validation_0-logloss:0.70115
[133]	validation_0-logloss:0.70105
[134]	validation_0-logloss:0.70107
[135]	validation_0-logloss:0.70113
[136]	validation_0-logloss:0.70118
[137]	validation_0-logloss:0.70115
[138]	validation_0-logloss:0.70112
[139]	validation_0-logloss:0.70118
[140]	validation_0-logloss:0.70110
[141]	validation_0-logloss:0.70111
[142]	validation_0-logloss:0.70104
[143]	validation_0-logloss:0.70109
[144]	validation_0-logloss:0.70103
[145]	validation_0-logloss:0.70104
[146]	validation_0-logloss:0.70123
[147]	validation_0-logloss:0.70139
[148]	validation_0-logloss:0.70132
[149]	validation_0-logloss:0.70132
[150]	validation_0-logloss:0.70128
[151]	validation_0-logloss:0.70140
[152]	validation_0-logloss:0.70149
[153]	validation_0-logloss:0.70148
[154]	validation_0-logloss:0.70165
[155]	validation_0-logloss:0.70163
[156]	validation_0-logloss:0.70169
[157]	validation_0-logloss:0.70165
[158]	validation_0-logloss:0.70175
[159]	validation_0-logloss:0.70175
[160]	validation_0-logloss:0.70173
[161]	validation_0-logloss:0.70175
[162]	validation_0-logloss:0.70174
[163]	validation_0-logloss:0.70177
[164]	validation_0-logloss:0.70180
[165]	validation_0-logloss:0.70180
[166]	validation_0-logloss:0.70173
[167]	validation_0-logloss:0.70153
[168]	validation_0-logloss:0.70162
[169]	validation_0-logloss:0.70166
[170]	validation_0-logloss:0.70178
[171]	validation_0-logloss:0.70197
[172]	validation_0-logloss:0.70193
[173]	validation_0-logloss:0.70208
[174]	validation_0-logloss:0.70210
[175]	validation_0-logloss:0.70230
[176]	validation_0-logloss:0.70228
[177]	validation_0-logloss:0.70225
[178]	validation_0-logloss:0.70226
[179]	validation_0-logloss:0.70227
[180]	validation_0-logloss:0.70232
[181]	validation_0-logloss:0.70243
[182]	validation_0-logloss:0.70248
[183]	validation_0-logloss:0.70250
[184]	validation_0-logloss:0.70273
[185]	validation_0-logloss:0.70290
[186]	validation_0-logloss:0.70282
[187]	validation_0-logloss:0.70275
[188]	validation_0-logloss:0.70283
[189]	validation_0-logloss:0.70294
[190]	validation_0-logloss:0.70289
[191]	validation_0-logloss:0.70297
[192]	validation_0-logloss:0.70302
[193]	validation_0-logloss:0.70300
[194]	validation_0-logloss:0.70322
[195]	validation_0-logloss:0.70302
[196]	validation_0-logloss:0.70307
[197]	validation_0-logloss:0.70321
[198]	validation_0-logloss:0.70334
[199]	validation_0-logloss:0.70346
[200]	validation_0-logloss:0.70368
[201]	validation_0-logloss:0.70378
[202]	validation_0-logloss:0.70371
[203]	validation_0-logloss:0.70369
[204]	validation_0-logloss:0.70379
[205]	validation_0-logloss:0.70381
[206]	validation_0-logloss:0.70391
[207]	validation_0-logloss:0.70388
[208]	validation_0-logloss:0.70379
[209]	validation_0-logloss:0.70387
[210]	validation_0-logloss:0.70390
[211]	validation_0-logloss:0.70392
[212]	validation_0-logloss:0.70401
[213]	validation_0-logloss:0.70395
[214]	validation_0-logloss:0.70391
[215]	validation_0-logloss:0.70412
[216]	validation_0-logloss:0.70417
[217]	validation_0-logloss:0.70431
[218]	validation_0-logloss:0.70426
[219]	validation_0-logloss:0.70434
[220]	validation_0-logloss:0.70440
[221]	validation_0-logloss:0.70458
[222]	validation_0-logloss:0.70452
[223]	validation_0-logloss:0.70453
[224]	validation_0-logloss:0.70449
[225]	validation_0-logloss:0.70438
[226]	validation_0-logloss:0.70432
[227]	validation_0-logloss:0.70455
[228]	validation_0-logloss:0.70449
[229]	validation_0-logloss:0.70447
[230]	validation_0-logloss:0.70452
[231]	validation_0-logloss:0.70450
[232]	validation_0-logloss:0.70444
[233]	validation_0-logloss:0.70443
[234]	validation_0-logloss:0.70452
[235]	validation_0-logloss:0.70445
[236]	validation_0-logloss:0.70437
[237]	validation_0-logloss:0.70453
[238]	validation_0-logloss:0.70458
[239]	validation_0-logloss:0.70441
[240]	validation_0-logloss:0.70445
[241]	validation_0-logloss:0.70445
[242]	validation_0-logloss:0.70460
[243]	validation_0-logloss:0.70473
[244]	validation_0-logloss:0.70471
[245]	validation_0-logloss:0.70478
[246]	validation_0-logloss:0.70476
[247]	validation_0-logloss:0.70481
[248]	validation_0-logloss:0.70502
[249]	validation_0-logloss:0.70495
[250]	validation_0-logloss:0.70489
[251]	validation_0-logloss:0.70489
[252]	validation_0-logloss:0.70491
[253]	validation_0-logloss:0.70506
[254]	validation_0-logloss:0.70514
[255]	validation_0-logloss:0.70523
[256]	validation_0-logloss:0.70526
[257]	validation_0-logloss:0.70529
[258]	validation_0-logloss:0.70541
[259]	validation_0-logloss:0.70538
[260]	validation_0-logloss:0.70549
[261]	validation_0-logloss:0.70554
[262]	validation_0-logloss:0.70548
[263]	validation_0-logloss:0.70554
[264]	validation_0-logloss:0.70534
[265]	validation_0-logloss:0.70543
[266]	validation_0-logloss:0.70551
[267]	validation_0-logloss:0.70567
[268]	validation_0-logloss:0.70576
[269]	validation_0-logloss:0.70577
[270]	validation_0-logloss:0.70574
[271]	validation_0-logloss:0.70572
[272]	validation_0-logloss:0.70574
[273]	validation_0-logloss:0.70591
[274]	validation_0-logloss:0.70600
[275]	validation_0-logloss:0.70596
[276]	validation_0-logloss:0.70614
[277]	validation_0-logloss:0.70625
[278]	validation_0-logloss:0.70635
[279]	validation_0-logloss:0.70632
[280]	validation_0-logloss:0.70639
[281]	validation_0-logloss:0.70642
[282]	validation_0-logloss:0.70654
[283]	validation_0-logloss:0.70659
[284]	validation_0-logloss:0.70658
[285]	validation_0-logloss:0.70667
[286]	validation_0-logloss:0.70670
[287]	validation_0-logloss:0.70666
[288]	validation_0-logloss:0.70666
[289]	validation_0-logloss:0.70679
[290]	validation_0-logloss:0.70682
[291]	validation_0-logloss:0.70688
[292]	validation_0-logloss:0.70688
[293]	validation_0-logloss:0.70702
[294]	validation_0-logloss:0.70700
[295]	validation_0-logloss:0.70711
[296]	validation_0-logloss:0.70700
[297]	validation_0-logloss:0.70717
[298]	validation_0-logloss:0.70715
[299]	validation_0-logloss:0.70715
[300]	validation_0-logloss:0.70720
[301]	validation_0-logloss:0.70738
[302]	validation_0-logloss:0.70735
[303]	validation_0-logloss:0.70725
[304]	validation_0-logloss:0.70724
[305]	validation_0-logloss:0.70746
[306]	validation_0-logloss:0.70761
[307]	validation_0-logloss:0.70759
[308]	validation_0-logloss:0.70766
[309]	validation_0-logloss:0.70765
[310]	validation_0-logloss:0.70767
[311]	validation_0-logloss:0.70760
[312]	validation_0-logloss:0.70766
[313]	validation_0-logloss:0.70764
[314]	validation_0-logloss:0.70787
[315]	validation_0-logloss:0.70797
[316]	validation_0-logloss:0.70807
[317]	validation_0-logloss:0.70814
[318]	validation_0-logloss:0.70806
[319]	validation_0-logloss:0.70808
[320]	validation_0-logloss:0.70808
[321]	validation_0-logloss:0.70822
[322]	validation_0-logloss:0.70819
[323]	validation_0-logloss:0.70820
[324]	validation_0-logloss:0.70815
[325]	validation_0-logloss:0.70800
[326]	validation_0-logloss:0.70800
[327]	validation_0-logloss:0.70804
[328]	validation_0-logloss:0.70800
[329]	validation_0-logloss:0.70787
[330]	validation_0-logloss:0.70788
[331]	validation_0-logloss:0.70786
[332]	validation_0-logloss:0.70789
[333]	validation_0-logloss:0.70787
[334]	validation_0-logloss:0.70786
[335]	validation_0-logloss:0.70796
[336]	validation_0-logloss:0.70792
[337]	validation_0-logloss:0.70788
[338]	validation_0-logloss:0.70809
[339]	validation_0-logloss:0.70802
[340]	validation_0-logloss:0.70805
[341]	validation_0-logloss:0.70807
[342]	validation_0-logloss:0.70825
[343]	validation_0-logloss:0.70832
[344]	validation_0-logloss:0.70831
[345]	validation_0-logloss:0.70829
[346]	validation_0-logloss:0.70844
[347]	validation_0-logloss:0.70848
[348]	validation_0-logloss:0.70841
[349]	validation_0-logloss:0.70848
[350]	validation_0-logloss:0.70854
[351]	validation_0-logloss:0.70866
[352]	validation_0-logloss:0.70870
[353]	validation_0-logloss:0.70879
[354]	validation_0-logloss:0.70884
[355]	validation_0-logloss:0.70891
[356]	validation_0-logloss:0.70898
[357]	validation_0-logloss:0.70894
[358]	validation_0-logloss:0.70893
[359]	validation_0-logloss:0.70895
[360]	validation_0-logloss:0.70907
[361]	validation_0-logloss:0.70923
[362]	validation_0-logloss:0.70924
[363]	validation_0-logloss:0.70930
[364]	validation_0-logloss:0.70927
[365]	validation_0-logloss:0.70943
[366]	validation_0-logloss:0.70951
[367]	validation_0-logloss:0.70971
[368]	validation_0-logloss:0.70976
[369]	validation_0-logloss:0.70991
[370]	validation_0-logloss:0.70987
[371]	validation_0-logloss:0.70999
[372]	validation_0-logloss:0.71014
[373]	validation_0-logloss:0.71017
[374]	validation_0-logloss:0.71014
[375]	validation_0-logloss:0.71019
[376]	validation_0-logloss:0.71018
[377]	validation_0-logloss:0.71018
[378]	validation_0-logloss:0.71021
[379]	validation_0-logloss:0.71020
[380]	validation_0-logloss:0.71032
[381]	validation_0-logloss:0.71046
[382]	validation_0-logloss:0.71044
[383]	validation_0-logloss:0.71039
[384]	validation_0-logloss:0.71025
[385]	validation_0-logloss:0.71018
[386]	validation_0-logloss:0.71019
[387]	validation_0-logloss:0.71015
[388]	validation_0-logloss:0.71029
[389]	validation_0-logloss:0.71041
[390]	validation_0-logloss:0.71036
[391]	validation_0-logloss:0.71037
[392]	validation_0-logloss:0.71036
[393]	validation_0-logloss:0.71043
[394]	validation_0-logloss:0.71043
[395]	validation_0-logloss:0.71023
[396]	validation_0-logloss:0.71042
[397]	validation_0-logloss:0.71043
[398]	validation_0-logloss:0.71042
[399]	validation_0-logloss:0.71042
[400]	validation_0-logloss:0.71046
[401]	validation_0-logloss:0.71067
[402]	validation_0-logloss:0.71067
[403]	validation_0-logloss:0.71076
[404]	validation_0-logloss:0.71078
[405]	validation_0-logloss:0.71075
[406]	validation_0-logloss:0.71087
[407]	validation_0-logloss:0.71082
[408]	validation_0-logloss:0.71087
[409]	validation_0-logloss:0.71086
[410]	validation_0-logloss:0.71106
[411]	validation_0-logloss:0.71104
[412]	validation_0-logloss:0.71094
[413]	validation_0-logloss:0.71087
[414]	validation_0-logloss:0.71100
[415]	validation_0-logloss:0.71094
[416]	validation_0-logloss:0.71093
[417]	validation_0-logloss:0.71100
[418]	validation_0-logloss:0.71098
[419]	validation_0-logloss:0.71113
[420]	validation_0-logloss:0.71120
[421]	validation_0-logloss:0.71127
[422]	validation_0-logloss:0.71125
[423]	validation_0-logloss:0.71121
[424]	validation_0-logloss:0.71131
[425]	validation_0-logloss:0.71123
[426]	validation_0-logloss:0.71122
[427]	validation_0-logloss:0.71109
[428]	validation_0-logloss:0.71119
[429]	validation_0-logloss:0.71125
[430]	validation_0-logloss:0.71127
[431]	validation_0-logloss:0.71137
[432]	validation_0-logloss:0.71160
[433]	validation_0-logloss:0.71156
[434]	validation_0-logloss:0.71162
[435]	validation_0-logloss:0.71156
[436]	validation_0-logloss:0.71162
[437]	validation_0-logloss:0.71156
[438]	validation_0-logloss:0.71167
[439]	validation_0-logloss:0.71182
[440]	validation_0-logloss:0.71181
[441]	validation_0-logloss:0.71187
[442]	validation_0-logloss:0.71189
[443]	validation_0-logloss:0.71189
[444]	validation_0-logloss:0.71182
[445]	validation_0-logloss:0.71187
[446]	validation_0-logloss:0.71201
[447]	validation_0-logloss:0.71209
[448]	validation_0-logloss:0.71216
[449]	validation_0-logloss:0.71226
[450]	validation_0-logloss:0.71232
[451]	validation_0-logloss:0.71227
[452]	validation_0-logloss:0.71238
[453]	validation_0-logloss:0.71250
[454]	validation_0-logloss:0.71260
[455]	validation_0-logloss:0.71268
[456]	validation_0-logloss:0.71256
[457]	validation_0-logloss:0.71258
[458]	validation_0-logloss:0.71260
[459]	validation_0-logloss:0.71275
[460]	validation_0-logloss:0.71295
[461]	validation_0-logloss:0.71309
[462]	validation_0-logloss:0.71322
[463]	validation_0-logloss:0.71321
[464]	validation_0-logloss:0.71310
[465]	validation_0-logloss:0.71330
[466]	validation_0-logloss:0.71332
[467]	validation_0-logloss:0.71341
[468]	validation_0-logloss:0.71343
[469]	validation_0-logloss:0.71346
[470]	validation_0-logloss:0.71369
[471]	validation_0-logloss:0.71390
[472]	validation_0-logloss:0.71394
[473]	validation_0-logloss:0.71393
[474]	validation_0-logloss:0.71400
[475]	validation_0-logloss:0.71414
[476]	validation_0-logloss:0.71399
[477]	validation_0-logloss:0.71409
[478]	validation_0-logloss:0.71422
[479]	validation_0-logloss:0.71445
[480]	validation_0-logloss:0.71451
[481]	validation_0-logloss:0.71440
[482]	validation_0-logloss:0.71445
[483]	validation_0-logloss:0.71424
[484]	validation_0-logloss:0.71435
[485]	validation_0-logloss:0.71446
[486]	validation_0-logloss:0.71439
[487]	validation_0-logloss:0.71445
[488]	validation_0-logloss:0.71449
[489]	validation_0-logloss:0.71456
[490]	validation_0-logloss:0.71452
[491]	validation_0-logloss:0.71450
[492]	validation_0-logloss:0.71452
[493]	validation_0-logloss:0.71462
[494]	validation_0-logloss:0.71463
[495]	validation_0-logloss:0.71458
[496]	validation_0-logloss:0.71468
[497]	validation_0-logloss:0.71486
[498]	validation_0-logloss:0.71493
[499]	validation_0-logloss:0.71504

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [40]:
from sklearn.metrics import classification_report, confusion_matrix

predictions = model.predict(X_test)

print("Classification Report:\n")
print(classification_report(y_test, predictions, target_names=["Down/No Gain", "Up"]))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, predictions))

Classification Report:

              precision    recall  f1-score   support

Down/No Gain       0.59      0.56      0.57      3128
          Up       0.44      0.46      0.45      2295

    accuracy                           0.52      5423
   macro avg       0.51      0.51      0.51      5423
weighted avg       0.52      0.52      0.52      5423


Confusion Matrix:

[[1751 1377]
 [1229 1066]]